✨ feat: Integrate with UI Plaid.
SPN-DAO/monorepo pull request #12
Opened 2023-02-26 23:07 UTC by joartola

2023-02-26 23:14 UTC, joartola commented
https://user-images.githubusercontent.com/31057068/221443269-14a8c46c-ebd2-4864-a671-ed49193e112c.mov

2023-02-27 14:54 UTC, kgelpes requested changes

2023-02-27 14:54 UTC, kgelpes commented on webapp/components/JoinDALNButton.tsx
> +  const sendPublicTokenToBackend = useCallback(
We could call this using react query, probably better for handling states

2023-02-27 14:54 UTC, kgelpes commented on webapp/hooks/useCreateLinkToken.tsx
> +export default useCreateLinkToken;
this file could be replaced with useQuery from react-query

2023-02-27 21:54 UTC, kgelpes approved these changes
looks good!

2023-02-27 22:34 UTC, merged